version: '3'
services:
  webapp:
    image: hamzaghafran/test_project_webapp
    command: sh -c "sleep 120s ; python3 ./app1.py"
    ports:
      - "5000:5000"
    depends_on:
      - db
    
    
  db:
    image: hamzaghafran/test_project_db
    ports:
 
      - "32000:3306"
    environment:

      MYSQL_ROOT_PASSWORD: 'Hamza#410'
    volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro

